config/routes.rb
JaneslunchCom::Application.routes.draw do

  get "info/about"

  get "info/contact"

  get "info/terms"

  get "info/security"

  get "info/suggestions"

  root :to => "site#index"
  
  resources :user do
    member do
        get 'join'
        get 'ignore'
      end
  end
      
  resources :groups 
  
  resources :items

  resources :ordr_accounts
  
  devise_for :users #:controllers => { :invitations => 'users/invitations' }

  get "/groups/:id/invitations/new" => "invitations#new", :as => "new_group_invitation" 

  post "groups/:id/invitations/create" => "invitations#create", :as => "create_group_invitation"

  # get "groups/:id/invitations/accept" => "invitations#edit", :as => "accept_group_invitation" 

  # devise_scope :user do 
  #   match "/groups/:id/invitations/new", :to => "users/invitations#new", :via => "get", :as => "new_group_invitation"
  # end  

  # devise_scope :user do
  #   match "groups/:id/invitations/accept", :to => "users/invitations#edit", :via => "get", :as => "accept_group_invitation"
  # end  

  # devise_scope :user do
  #   match "groups/:id/invitations/create", :to => "users/invitations#create", :via => "post", :as => "create_group_invitation"
  # end

  get "/u" => "user#index", :as => :user_root
  get "/u/edit" => "user#edit"
  post "/u/card" => "user#update_cc"


  match '/:groupname' => "groups#show", :as => 'group/show'
  post '/:groupname/order' => "orders#create", :as => 'create_order'

end

app/models/group.rb
class Group < ActiveRecord::Base

  attr_accessible :name, :lunch_time, :group_orders, :address_attributes

  validates :name, :uniqueness => true

  before_save :convert_time

  belongs_to :address
  accepts_nested_attributes_for :address

  has_and_belongs_to_many :users
  has_many :group_orders

  def convert_time
     @lunch_time = DateTime.parse(lunch_time.to_s)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!

  @@meat = %w(beef chicken pork ham tongue meatball bacon sausage salmon pepperoni tuna halibut shrimp)

  def index
    @group_name = params['groupname']
  end

  def new
    @group = Group.new
    @group.build_address
  end

  def create
    if user_signed_in?
      @group = Group.new(params[:group])
      @group.users << current_user
      if @group.save
        redirect_to "/#{@group.name}", :notice => 'Your group is ready!'
      else
        render 'new'
      end
    end
  end

  def show
    get_group
    if @group
      if @group.group_orders.from_today.size == 0
        new_group_order
        @group.group_orders << @group_order
      else
        @group_order = @group.group_orders.from_today.first
      end

      unless @group_order.restaurant_id
        redirect_to '/u', :notice => 'Sorry, it looks like no one is delivering to your location at this time.'
      end
    else
      redirect_to '/u'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to groups_path, :notice => 'You updated your group!'
    else
    end
  end

  def get_group
    @group = Group.where(:name => params['groupname']).first
    # @group = Group.find(1)
  end

  def new_group_order
    @group_order = GroupOrder.new
    @group_order.group = @group

    if get_restaurant
      get_choices
    end
  end

  def get_restaurant
    time = @group.lunch_time
    # @TODO - Get time zone support sorted
    time = DateTime.parse(time + ' Eastern')
    address = @group.address.address_for_ordr
    begin
      restaurants = $ordrin.restaurant.get_delivery_list(time, address)
      id = restaurants.sample['id'] || 0
    rescue Exception => e
      p "There was an error pulling a restaurant - #{e}"
      return false
    end

    restaurant_controller = RestaurantController.new
    restaurant = restaurant_controller.create(id)
    # raise restaurant.inspect
    @group_order.restaurant = restaurant
    restaurant.save
  end

  def get_choices
    get_restaurant
    meat_choice = get_item(@@meat)
    @group_order.items << meat_choice
    meat_choice.save
    chicken_choice = get_item(%w(chicken))
    @group_order.items << chicken_choice
    chicken_choice.save
    vegie_choice = get_item_thats_not(@@meat)
    @group_order.items << vegie_choice
    vegie_choice.save
  end

  def get_item(keywords)
    options = []
    keywords.each do |keyword|
      @group_order.restaurant.items.each do |item|
        if (item.name.downcase.include? keyword) || (item.descrip.downcase.include? keyword)
          options << item
        end
      end
    end
    options.sample
  end

  def get_item_thats_not(keywords)
    options = []
    keywords.each do |keyword|
      @group_order.restaurant.items.each do |item|
        unless (item.name.downcase.include? keyword) || (item.descrip.downcase.include? keyword)
          options << item
        end
      end
    end
    options.sample
  end


end

app/helpers/group_helper.rb
module GroupHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

end

app/views/groups/edit.html.erb
<h1>Let's edit your Group</h1>

<%= render :template => 'shared/form' %>

app/views/groups/index.html.erb
<h1>All Groups</h1>

<br>
<% Group.all.each do |group| %>
  <p><%= group.name %>   <%= link_to 'edit', edit_group_path(group)%>
</p>
<% end %>

<br>
<%= link_to 'Create New Group', new_group_path, :class => 'btn btn-large btn-success' %>

app/views/groups/new.html.erb
<h1>Let's Make a New Group</h1>

<%= render :template => 'shared/form' %>

app/views/groups/show.html.erb
<h1>- Pick your lunch -</h1>
<h2><%= @group_order.restaurant.name %></h2>

<div class="choices-wrapper row">
  <% @group_order.items.each do |item| %>

    <div id="<%= item.id %>" class="choice span4">
      <h3><%= item.name %></h3>
      <p class="description"><%= item.descrip %></p>
      <span class="price"><%= number_to_currency(item.price) %></span>
    </div>
  <% end %>

</div>

  <a href="#option-modal" id="pop-modal" class="btn btn-large btn-success make-order" data-toggle="modal" style="display: none;">Order!</a>

<div class="links" style="display: none;">
  <%= link_to 'Edit Group', edit_group_path(:id => @group.id) %>
  <%= link_to 'Invite Users to Join Group', new_group_invitation_path(:id => @group.id) %>
</div>

<div id="option-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <div id="option-column" class="left"></div>
    <div class="right">
      <h3>Tip</h3>
      $<input id="tip" type="text" placeholder="Enter a tip">
      <ul class="tip-calc">
        <li class="0.15">15%</li>
        <li class="0.20">20%</li>
        <li class="0.25">25%</li>
      </ul>
      <h3>Total</h3>
      <h3 id="total"></h3>

      <a id="submit-order" class="btn btn-block btn-success" data-dismiss="modal" aria-hidden="true">Submit Order</a>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

<script>
  $(function() {
    window.groupOrder = <%= @group_order.id %>;
    window.group = '<%= @group.name %>';
  })
</script>